name: Build and Publish Docker Image

on:
  push:
    branches: ["dev", "main"]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare image name
        id: prep
        run: |
          image="ghcr.io/${GITHUB_REPOSITORY,,}"
          echo "image=$image" >> "$GITHUB_OUTPUT"

      - name: Determine branch tag
        id: branch_tag
        run: |
          if [ "${GITHUB_REF}" = "refs/heads/main" ] || [ "${GITHUB_EVENT_NAME}" = "release" ]; then
            echo "branch_tag=type=raw,value=latest" >> "$GITHUB_OUTPUT"
          else
            echo "branch_tag=type=raw,value=dev" >> "$GITHUB_OUTPUT"
          fi
          
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.prep.outputs.image }}
          tags: |
            type=raw,value=${{ github.run_number }}
            ${{ steps.branch_tag.outputs.branch_tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
